# ------------------------------------------------------
# MaximoCon, segunda, jun 20, 2022 08:50:13
# Objetivo: Labtrans script to add weekly work loggings on jm_weeklogging app
# Autor: João Vitor de Oliveira Mendes
# ------------------------------------------------------

from java.util import Calendar
from java.lang import System
from java.text import SimpleDateFormat
from psdi.server import MXServer

#Add a new JM_WORKLOGGING
def addWLogging(weekNumber, startDate):
    wLogMboSet = MXServer.getMXServer().getMboSet('JM_WORKLOGGING', mbo.getUserInfo()) #MXSERVER since its incorrect to save from a relationship
    wLogMbo = wLogMboSet.add()
    wLogMbo.setValue('ORGID', 'EAGLENA', mbo.NOACCESSCHECK)
    wLogMbo.setValue('SITEID', 'BEDFORD', mbo.NOACCESSCHECK)
    wLogMbo.setValue('JM_LABORCODE', mbo.getString('LABORCODE'), mbo.NOACCESSCHECK)
    wLogMbo.setValue('JM_WEEKNUMBER', weekNumber, mbo.NOACCESSCHECK)
    wLogMbo.setValue('JM_WEEKSTARTDATE', startDate, mbo.NOACCESSCHECK)
    wLogMboSet.save()

#Add a new JM_WORKENTRY
def addWEntry(dayOfWeek):
    wLogMboSet = MXServer.getMXServer().getMboSet('JM_WORKLOGGING', mbo.getUserInfo())
    wLogMboSet.setWhere(
            'jm_laborcode = \'' + mbo.getString('LABORCODE') + '\''
            + ' and convert(varchar(20), jm_weekstartdate, 23) = \'' + startDate + '\'')
    wLogMboSet.reset()
    wLogMbo = wLogMboSet.moveFirst()
    wEntryMboSet = wLogMbo.getMboSet('JM_WORKENTRY')
    wEntryMboSet.setWhere('jm_wonum = \'' + mbo.getString('WONUM') + '\' and jm_worknumber = \'' + wLogMbo.getString('JM_WORKNUMBER') + '\'')
    wEntryMboSet.reset()
    
    wEntryMbo = wEntryMboSet.add()
    wEntryMbo.setValue('JM_WONUM', mbo.getString('WONUM'), mbo.NOACCESSCHECK)
    wEntryMbo.setValue('JM_ACTUAL' + str(dayOfWeek - 1), mbo.getFloat('REGULARHRS'), mbo.NOACCESSCHECK)
    wEntryMbo.setValue('ORGID', wLogMbo.getString('ORGID'), mbo.NOACCESSCHECK)
    wEntryMbo.setValue('SITEID', wLogMbo.getString('SITEID'), mbo.NOACCESSCHECK)
    wEntryMbo.setValue('JM_WORKNUMBER', wLogMbo.getString('JM_WORKNUMBER'), mbo.NOACCESSCHECK)
    wEntryMbo.setValue('JM_WORKLOCATION' + str(dayOfWeek - 1), mbo.getString('LOCATION'), mbo.NOACCESSCHECK)
    wEntryMbo.setValue('JM_REMARKSTS' + str(dayOfWeek - 1), 'Entry generated by labtrans', mbo.NOACCESSCHECK)
    mbo.setValue('JM_ENTRYID', wEntryMbo.getString('JM_WORKENTRYID') + str(dayOfWeek - 1), mbo.NOACCESSCHECK)
    wEntryMboSet.save()

'''Save lp - add, update | before save'''
#app is necessary to trigger lp only when triggered in labtrans app
if launchPoint == 'SAVE' and app:
    if mbo.isNull('WONUM'):
        service.error('JM_WORKLOG', 'JM_NeedToInsertWo')
    else:
        woMboSet = mbo.getMboSet('$WORKORDER',
        'WORKORDER',
        'STATUS in (' +
        'select value from synonymdomain where domainid = \'WOSTATUS\'' +
        ' and maxvalue not in (\'CAN\',\'CLOSE\',\'HISTEDIT\',\'WAPPR\'))' +
        ' and istask = 0' +
        ' and wonum = \'' + mbo.getString('WONUM') + '\'')
        if woMboSet.isEmpty():
            service.error('JM_WORKLOG', 'JM_NeedToInsertWo')
        
    cal = Calendar.getInstance()
    cal.setTime(mbo.getDate('STARTDATE'))
    dayOfWeek = daySum = cal.get(Calendar.DAY_OF_WEEK)
    if dayOfWeek == 1:
        daySum += 7
    cal.add(Calendar.DATE, 2 - daySum)
    
    startDateFormater = SimpleDateFormat('yyyy-MM-dd')
    startDate = startDateFormater.format(cal.getTime())
    
    weeksMboSet = MXServer.getMXServer().getMboSet('WEEKS', mbo.getUserInfo())
    weeksMboSet.setWhere('WEEK_START = \'' + startDate + '\'')
    weeksMboSet.reset()
    
    cal.add(Calendar.DATE, -4)
    weekOfYear = str(cal.get(Calendar.WEEK_OF_YEAR))
    weekNumber = 'WEEK ' + weekOfYear + ' - ' + str(cal.get(Calendar.YEAR))
    cal.add(Calendar.DATE, 4)
    
    if weeksMboSet.isEmpty():
        weekMbo = weeksMboSet.add()
        weekMbo.setValue('ORGID', 'EAGLENA', mbo.NOACCESSCHECK)
        weekMbo.setValue('SITEID', 'BEDFORD', mbo.NOACCESSCHECK)
        weekMbo.setValue('WEEK_START', startDate, mbo.NOACCESSCHECK)
        cal.add(Calendar.DATE, 6)
        weekMbo.setValue('WEEK', weekNumber, mbo.NOACCESSCHECK)
        endDate = startDateFormater.format(cal.getTime())
        weekMbo.setValue('WEEK_END', endDate, mbo.NOACCESSCHECK)
        weeksMboSet.save()
        addWLogging(weekNumber, startDate)
        addWEntry(dayOfWeek)
    else:
        wLogMboSet = MXServer.getMXServer().getMboSet('JM_WORKLOGGING', mbo.getUserInfo())
        wLogMboSet.setWhere(
            'jm_laborcode = \'' + mbo.getString('LABORCODE') + '\''
            + ' and convert(varchar(20), jm_weekstartdate, 23) = \'' + startDate + '\'')
        wLogMboSet.reset()
        if wLogMboSet.isEmpty():
            addWLogging(weekNumber, startDate)
            addWEntry(dayOfWeek)
        else:
            wLogMbo = wLogMboSet.moveFirst()
            wEntryMboSet = wLogMbo.getMboSet('JM_WORKENTRY')
            wEntryMboSet.setWhere('jm_wonum = \'' + mbo.getString('WONUM') + '\' and jm_worknumber = \'' + wLogMbo.getString('JM_WORKNUMBER') + '\'')
            wEntryMboSet.reset()
            if wEntryMboSet.isEmpty():
                addWEntry(dayOfWeek)
            else:
                wEntryMbo = wEntryMboSet.moveFirst()
                wEntryMbo.setValue('JM_WONUM', mbo.getString('WONUM'), mbo.NOACCESSCHECK)
                wEntryMbo.setValue('JM_ACTUAL' + str(dayOfWeek - 1), mbo.getFloat('REGULARHRS'), mbo.NOACCESSCHECK)
                wEntryMbo.setValue('JM_WORKLOCATION' + str(dayOfWeek - 1), mbo.getString('LOCATION'), mbo.NOACCESSCHECK)
                wEntryMbo.setValue('JM_REMARKSTS' + str(dayOfWeek - 1), 'Entry generated by labtrans', mbo.NOACCESSCHECK)
                mbo.setValue('JM_ENTRYID', wEntryMbo.getString('JM_WORKENTRYID') + str(dayOfWeek - 1), mbo.NOACCESSCHECK)
                if mbo.getBoolean('GENAPPRSERVRECEIPT'): wEntryMbo.setValue('JM_WORKSTATUS' + str(dayOfWeek - 1), 'APPROVED', mbo.NOACCESSCHECK)
                wEntryMboSet.save()

'''Save lp - add, update, delete | after save'''
if launchPoint == 'AFT_SAVE'  and app:
    cal = Calendar.getInstance()
    cal.setTime(mbo.getDate('STARTDATE'))
    dayOfWeek = daySum = cal.get(Calendar.DAY_OF_WEEK)
    entryId = mbo.getString('jm_entryid')
    wEntryMboSet = MXServer.getMXServer().getMboSet('JM_WORKENTRY', mbo.getUserInfo())
    wEntryMboSet.setWhere('jm_workentryid = ' + entryId[:-1].replace('.', ''))
    wEntryMboSet.reset()
    if ondelete:
        wEntryMbo = wEntryMboSet.moveFirst()
        while wEntryMbo:
            if wEntryMbo.getString('JM_WORKSTATUS' + str(dayOfWeek - 1)) == 'SUBMITTED':
                wEntryMbo.setValue('JM_WORKSTATUS' + str(dayOfWeek - 1), 'IN PROGRESS', mbo.NOACCESSCHECK)
                wEntryMbo = wEntryMboSet.moveNext()

        wEntryMboSet.save()
    else:
        if entryId:
            wEntryMbo = wEntryMboSet.moveFirst()
            if wEntryMbo:
                if wEntryMbo.getString('JM_WORKSTATUS' + str(dayOfWeek - 1)) not in ('SUBMITTED', 'APPROVED'):
                    wEntryMbo.setValue('JM_WORKSTATUS' + str(dayOfWeek - 1), 'SUBMITTED', mbo.NOACCESSCHECK)
                    wEntryMboSet.save()

    wEntryMboSet.reset()
    wEntryMbo = wEntryMboSet.moveFirst()
    wLogMboSet = mbo.getMboSet('JM_WORKLOGGING')
    wLogMbo = wLogMboSet.moveFirst()

    if wLogMbo:
        qtt = 0
        statusDict = {
            'CANCELLED': 0,
            'NOT STARTED': 0,
            'IN PROGRESS': 0,
            'SUBMITTED': 0,
            'APPROVED': 0
        }
        while wEntryMbo:
            statusDict[wEntryMbo.getString('JM_WORKSTATUS')] += 1
            qtt += 1
            wEntryMbo = wEntryMboSet.moveNext()
        if statusDict['CANCELLED'] == qtt:
            wLogMbo.setValue('JM_STATUS', 'CANCELLED', mbo.NOACCESSCHECK|mbo.NOVALIDATION)
        elif statusDict['NOT STARTED'] == qtt:
            wLogMbo.setValue('JM_STATUS', 'NOT STARTED', mbo.NOACCESSCHECK|mbo.NOVALIDATION)
        elif statusDict['SUBMITTED'] == qtt:
            wLogMbo.setValue('JM_STATUS', 'SUBMITTED', mbo.NOACCESSCHECK|mbo.NOVALIDATION)
        elif statusDict['APPROVED'] == qtt or statusDict['APPROVED'] + statusDict['CANCELLED'] == qtt:
            wLogMbo.setValue('JM_STATUS', 'APPROVED', mbo.NOACCESSCHECK|mbo.NOVALIDATION)
        elif statusDict['SUBMITTED'] + statusDict['APPROVED'] + statusDict['CANCELLED'] == qtt:
            wLogMbo.setValue('JM_STATUS', 'SUBMITTED', mbo.NOACCESSCHECK|mbo.NOVALIDATION)
        else:
            wLogMbo.setValue('JM_STATUS', 'IN PROGRESS', mbo.NOACCESSCHECK|mbo.NOVALIDATION)

        wEntryMboSet.reset()
        wEntryMbo = wEntryMboSet.moveFirst()

        if wEntryMboSet:
            totalSum = 0
            for i in range(7):
                wEntryMbo = wEntryMboSet.moveFirst()
                sum = 0

                while wEntryMbo:
                    sum += wEntryMbo.getFloat('JM_ACTUAL' + str(i))
                    wEntryMbo = wEntryMboSet.moveNext()

                wLogMbo.setValue('JM_TOTAL' + str(i), sum,  mbo.NOACCESSCHECK)
                totalSum += sum
            wLogMbo.setValue('JM_TOTACTUALHRS', totalSum,  mbo.NOACCESSCHECK)
        #wLogMboSet.save()
